### ISSUE TITLE
Capture Standard I/O and output it to the parent process

### ISSUE THREAD

**Issue by Starz0r** [itchio/elevate#3]
Is it possible to catch Standard I/O (stdin, stdout, stderr) and write to the parent process, in my case, the terminal? It would make this a lot better CLI tool and sudo replacement for Windows than just a tool to elevate GUI programs when needed.

**Comment by fasterthanlime** [comment]
Not in this (deprecated) project, but `butler elevate` will relay stdout and stderr: https://github.com/itchio/butler - it does so by [using named pipes on Windows](https://github.com/itchio/butler/blob/9a431b93be1308e857a5d0b6038dced481491f51/cmd/elevate/elevate_windows.go#L37-L52).
